import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderToStaticMarkup } from 'react-dom/server';
import { CEndApp } from '../../../../app/CEndApp';
import { tenureDays } from '../model/profile';
import { PcProfileCenter } from './PcProfileCenter';

describe('PC personal center', () => {
  it('matches the reference chrome, hero, home fields, and side cards', () => {
    const html = renderToStaticMarkup(<PcProfileCenter />);
    expect(html).toContain('class="kn-pc-me"');
    expect(html).toContain('class="topbar"');
    expect(html).toContain('aria-label="康尼机电"');
    expect(html).toContain('src="/profile/kone-logo.svg"');
    expect(html).toContain('工会新闻');
    expect(html).toContain('公司活动');
    expect(html).toContain('劳模成果');
    expect(html).toContain('知识百科');
    expect(html).toContain('微刊人物');
    expect(html).toContain('调研问卷');
    expect(html).toContain('心声建议');
    expect(html).toContain('人文关怀');
    expect(html).toContain('class="top-admin"');
    expect(html).toContain('>管理后台<');
    expect(html).toContain('aria-label="我的"');
    expect(html).toContain('个人主页');
    expect(html).toContain('我的互动');
    expect(html).toContain('class="hero"');
    expect(html).toContain('class="slab s1"');
    expect(html).toContain('>庄珊珊<');
    expect(html).toContain(`在职 ${tenureDays('2024-03-10')} 天`);
    expect(html).toContain('产品设计部');
    expect(html).toContain('>基本资料<');
    expect(html).toContain('>编辑资料<');
    expect(html).toContain('WH20240018');
    expect(html).toContain('关注体验细节，喜欢把复杂流程收成一条清楚的路径。');
    expect(html).toContain('交互设计');
    expect(html).toContain('摄影');
    expect(html).toContain('我的工会');
    expect(html).toContain('珊珊企业工会');
    expect(html).toContain('我的党组织');
    expect(html).toContain('党总支部');
    expect(html).toContain('个人成就');
    expect(html).toContain('>7<');
    expect(html).toContain('0 枚');
    expect(html).toContain('<a class="row is-go" href="#/c/pc/profile/medals">');
    expect(html).toContain('class="nav-dead"');
    expect(html).not.toContain('id="tabMore"');
    expect(html).toContain('我的活动');
    expect(html).toContain('我的帖子');
    expect(html).toContain('我的勋章');
    expect(html).toContain('我的关怀');
    expect(html).toContain('我的兴趣圈');
    expect(html).toContain('我的投票');
    expect(html).toContain('我的帮扶');
    expect(html).not.toContain('c-pc-shell');
  });

  it('renders interaction likes with tags and thumbs', () => {
    const html = renderToStaticMarkup(<PcProfileCenter tab="interactions" sub="likes" />);
    expect(html).toContain('class="page flat"');
    expect(html).toContain('class="ix-sub"');
    expect(html).toContain('中秋员工晚会');
    expect(html).toContain('大胃王比赛');
    expect(html).toContain('class="ix-tag is-act"');
    expect(html).toContain('class="ix-tag is-news"');
    expect(html).toContain('src="/activities/open-day.jpg"');
    expect(html).not.toContain('我的工会');
  });

  it('renders comments with author, text, and quoted card', () => {
    const html = renderToStaticMarkup(<PcProfileCenter tab="interactions" sub="comments" />);
    expect(html).toContain('晚会报名截止前提个醒，班组还差两个名额。');
    expect(html).toContain('class="ix-who"');
    expect(html).toContain('class="ix-comment"');
    expect(html).toContain('class="ix-ago"');
  });

  it('renders the edit form with locked system fields and save actions', () => {
    const html = renderToStaticMarkup(<PcProfileCenter tab="edit" />);
    expect(html).toContain('>编辑资料<');
    expect(html).toContain('系统同步，不可修改');
    expect(html).toMatch(/max[Ll]ength="20"/);
    expect(html).toContain('placeholder="如 江苏南京"');
    expect(html).toContain('回车添加');
    expect(html).toContain('>取消<');
    expect(html).toContain('>保存<');
    expect(html).toContain('class="btn btn-primary"');
  });

  it('keeps reference spacing tokens in CSS', () => {
    const css = readFileSync(join(dirname(fileURLToPath(import.meta.url)), './pc-profile.css'), 'utf8');
    expect(css).toContain('height: 56px');
    expect(css).toContain('background: rgba(255, 253, 249, .92)');
    expect(css).toContain('border-bottom: 1px solid #f3dcc4');
    expect(css).toContain('width: calc(100% - 160px)');
    expect(css).toContain('height: 168px');
    expect(css).toContain('background-color: #f6f3fb');
    expect(css).toContain('--primary: #1890ff');
    expect(css).toContain('grid-template-columns: minmax(0, 1fr) 300px');
    expect(css).toContain('width: 76px');
    expect(css).toContain('height: 48px');
    expect(css).toContain('color: #e85d04');
    expect(css).toContain('width: 120px; height: 80px');
    expect(css).toContain('height: min(680px, calc(100vh - 220px))');
    expect(css).toContain('.kn-pc-me .kn-pc-me-medals .c-incentive-pc-profile,');
    expect(css).toContain('.kn-pc-me .kn-pc-me-medals-honor .mobile-person-honor-page{');
    expect(css).toContain('overflow-y: auto');
    expect(css).toContain('grid-template-columns: minmax(0, 1fr) 720px');
  });

  it('mounts from CEndApp', () => {
    const html = renderToStaticMarkup(<CEndApp surface="pc" h5Page="profile" />);
    expect(html).toContain('class="kn-pc-me"');
    expect(html).toContain('>基本资料<');
    const ix = renderToStaticMarkup(
      <CEndApp surface="pc" h5Page="profile" profileTab="interactions" profileSub="likes" />,
    );
    expect(ix).toContain('中秋员工晚会');
  });

  it('lists company activities and interest-group activities on 我的活动', () => {
    const html = renderToStaticMarkup(<PcProfileCenter tab="activities" />);
    expect(html).toContain('>我的活动<');
    expect(html).toContain('class="mine-act-tag is-act"');
    expect(html).toContain('【活动】');
    expect(html).toContain('class="mine-act-tag is-ig"');
    expect(html).toContain('【兴趣圈活动】');
    expect(html).toContain('新员工入职训练营');
    expect(html).toContain('滨江 8K 夜跑');
    expect(html).toContain('通宵桌游马拉松');
    expect(html).toContain('class="mine-act-cover"');
    expect(html).toContain('src="/activities/onboarding.jpg"');
    expect(html).toContain('class="mine-act-time"');
    expect(html).toContain('class="mine-act-head"');
    expect(html).toMatch(
      /class="mine-act-head"[^>]*>[\s\S]*?class="mine-act-tag is-act"[^>]*>[\s\S]*?<h3>[\s\S]*?<\/h3>[\s\S]*?<\/div>[\s\S]*?class="mine-act-time"/,
    );
    expect(html).not.toContain('class="mine-act-main"');
    expect(html).toContain('08-31 09:30');
    expect(html).toContain('06月05日 19:30');
    expect(html).toContain('06月06日 22:00');
    expect(html).not.toContain('培训中心');
    expect(html).not.toContain('滨江园区');
    expect(html).not.toContain('总部 · 休闲区');
    expect(html).not.toContain('近郊 · 云栖谷');
    expect(html).toContain('>未开始<');
    expect(html).toContain('>进行中<');
    expect(html).toContain('>已结束<');
    expect(html).not.toContain('已报名');
    expect(html).not.toContain('已参加');
    expect(html).not.toContain('线上公益讲座');
    expect(html).not.toContain('周四羽毛球娱乐局');
    expect(html).not.toContain('周末连营徒步');
    expect(html).toContain('href="#/c/pc/');
    expect(html).not.toContain('class="nav-dead">我的活动<');
    expect(html).not.toContain('活动统计');
    expect(html).not.toContain('>活动报名<');
    const titles = [...html.matchAll(/class="item mine-act-row"[\s\S]*?<h3>([^<]*)<\/h3>/g)].map((match) => match[1]);
    expect(titles.indexOf('公益植树日')).toBeLessThan(titles.indexOf('新员工入职训练营'));
    expect(titles.indexOf('周四篮球夜')).toBeLessThan(titles.indexOf('新员工入职训练营'));
    expect(titles.indexOf('通宵桌游马拉松')).toBeLessThan(titles.indexOf('春季员工开放日'));
  });

  it('lists my posts, medals, and care on their tabs', () => {
    const posts = renderToStaticMarkup(<PcProfileCenter tab="posts" />);
    expect(posts).toContain('>我的帖子<');
    expect(posts).toContain('人体工学椅');
    expect(posts).toContain('低糖早餐');
    expect(posts).toContain('href="#/c/pc/forum-topic/');
    expect(posts).toContain('class="page flat"');
    expect(posts).not.toContain('class="side-col"');
    expect(posts).not.toContain('class="card-head"><h2>帖子</h2>');
    const medals = renderToStaticMarkup(<PcProfileCenter tab="medals" />);
    expect(medals).toContain('>我的勋章<');
    expect(medals).toContain('class="c-incentive-pc-profile honor-badge-collection"');
    expect(medals).toContain('累计积分');
    expect(medals).toContain('class="c-incentive-pc-profile-hero is-stats"');
    expect(medals).not.toContain('轨道交通事业部');
    expect(medals).not.toContain('林晓云');
    expect(medals).toContain('aria-label="勋章类型"');
    expect(medals).toContain('及时响应需求');
    expect(medals).toContain('class="honor-badge-grid"');
    expect(medals).toContain('data-badge-detail="modal"');
    expect(medals).toContain('desktop-employee-honor-wall');
    expect(medals).toContain('>勋章记录<');
    expect(medals).not.toContain('>勋章墙<');
    expect(medals).toContain('class="employee-honor-record"');
    expect((medals.match(/class="employee-honor-record"/g) ?? []).length).toBeGreaterThanOrEqual(6);
    expect(medals).toContain('2026 年 8 月');
    expect(medals).toContain('2026 年 7 月');
    expect(medals).toContain('2026 年 6 月');
    expect(medals).toContain('主动补位');
    expect(medals).toContain('培养新人');
    expect(medals).toContain('【公司表彰】');
    expect(medals).not.toContain('集团工会');
    expect(medals).not.toContain('employee-honor-wall-hero');
    expect(medals).not.toContain('年度标杆');
    expect(medals).not.toContain('class="card-head"><h2>勋章</h2>');
    const care = renderToStaticMarkup(<PcProfileCenter tab="care" />);
    expect(care).toContain('>我的关怀<');
    expect(care).toContain('还没有关怀记录');
    expect(care).not.toContain('生日快乐');
    expect(care).not.toContain('月满人团圆');
    expect(care).toContain('class="page flat"');
    expect(care).not.toContain('class="side-col"');
    expect(care).not.toContain('class="card-head"><h2>关怀</h2>');
    const circles = renderToStaticMarkup(<PcProfileCenter tab="circles" />);
    expect(circles).toContain('>我的兴趣圈<');
    expect(circles).toContain('城市夜跑团');
    expect(circles).toContain('周末徒步野行');
    expect(circles).toContain('桌游电竞局');
    expect(circles).toContain('class="mine-act-cover"');
    expect(circles).toContain('src="/activities/basketball.jpg"');
    expect(circles).toContain('src="/activities/share.jpg"');
    expect(circles).toContain('class="page flat"');
    expect(circles).not.toContain('随时都有空位，等你入座。');
    expect(circles).not.toContain('总部 · 滨江园区');
    expect(circles).not.toContain('近郊 · 多线路');
    expect(circles).not.toContain('总部 · 休闲区');
    expect(circles).not.toContain('class="card-head"><h2>兴趣圈</h2>');
    expect(circles).not.toContain('class="side-col"');
    expect(circles).not.toContain('摄影协会');
    expect(circles).not.toContain('深夜读书会');
    expect(circles).not.toContain('c-ig-intro-expand');
    expect(circles).not.toContain('id="tabMore"');
    const votes = renderToStaticMarkup(<PcProfileCenter tab="votes" />);
    expect(votes).toContain('>我的投票<');
    expect(votes).toContain('年度优秀作品展');
    expect(votes).toContain('一线匠心人物');
    expect(votes).toContain('部门团建目的地');
    expect(votes).not.toContain('食堂服务评价还差你一票');
    expect(votes).not.toContain('班组擂台赛');
    expect(votes).toContain('class="page flat"');
    expect(votes).not.toContain('class="side-col"');
    expect(votes).not.toContain('class="card-head"><h2>投票</h2>');
  });
});
