import { commentCount, type MomentRecord } from '../../activities/model/moment';

export const INTEREST_GROUP_MOMENT_MOCK_VERSION = 3;

export type InterestGroupMoment = Omit<MomentRecord, 'activityId'> & {
  groupId: number;
  activityId?: number;
};

export function interestGroupMomentCommentTotal(item: InterestGroupMoment): number {
  return commentCount(item);
}

export const initialInterestGroupMoments: InterestGroupMoment[] = [
  {
    id: 1,
    groupId: 1,
    activityId: 102,
    author: '江野',
    content: '初夏漫步打卡，夕阳刚好。',
    type: '图文类型',
    imageUrls: ['/activities/share.jpg'],
    status: '已通过',
    createdAt: '2026-06-02 19:30:00',
    updatedAt: '2026-06-02 19:30:00',
    likedBy: ['张悦', '周棠'],
    comments: [
      {
        id: 11,
        author: '周棠',
        content: '这张光线很好。',
        createdAt: '2026-06-02 20:10:00',
        replies: [{ id: 111, author: '江野', content: '江边风大，拍了好几张。', createdAt: '2026-06-02 20:18:00' }],
      },
    ],
  },
  {
    id: 2,
    groupId: 2,
    activityId: 201,
    author: '苏曼',
    content: '营地日出，值回早起。',
    type: '图文类型',
    imageUrls: ['/activities/onboarding.jpg', '/activities/share.jpg'],
    status: '待审核',
    createdAt: '2026-06-03 06:45:00',
    updatedAt: '2026-06-03 06:45:00',
    likedBy: [],
    comments: [],
  },
  {
    id: 3,
    groupId: 4,
    activityId: 401,
    author: '沈星',
    content: '昨晚狼人杀高光局。',
    type: '视频',
    imageUrls: [],
    videoUrl: '/activities/open-day.jpg',
    status: '已驳回',
    rejectReason: '画面模糊，请补清晰成片',
    createdAt: '2026-06-07 22:10:00',
    updatedAt: '2026-06-08 09:00:00',
    likedBy: [],
    comments: [],
  },
  {
    id: 4,
    groupId: 1,
    author: '张悦',
    content: '夜跑收工，江风把汗吹干。',
    type: '图文类型',
    imageUrls: ['/activities/basketball.jpg'],
    status: '已通过',
    createdAt: '2026-06-12 21:20:00',
    updatedAt: '2026-06-12 21:20:00',
    likedBy: ['江野', '周棠', '林浅'],
    comments: [],
  },
  {
    id: 5,
    groupId: 2,
    author: '陈产品',
    content: '连营第二天，溪边煮面最香。',
    type: '图文类型',
    imageUrls: ['/activities/onboarding.jpg', '/activities/share.jpg'],
    status: '已通过',
    createdAt: '2026-06-03 12:10:00',
    updatedAt: '2026-06-03 12:10:00',
    likedBy: ['苏曼', '张悦', '林浅', '周棠'],
    comments: [],
  },
  {
    id: 6,
    groupId: 3,
    author: '王芳',
    content: '书吧灯还亮着，围读散场合影。',
    type: '图文类型',
    imageUrls: ['/activities/webinar.jpg'],
    status: '已通过',
    createdAt: '2026-06-10 21:05:00',
    updatedAt: '2026-06-10 21:05:00',
    likedBy: ['周棠', '林浅'],
    comments: [],
  },
  {
    id: 7,
    groupId: 4,
    author: '黄码',
    content: '五黑翻盘，这把要回看十遍。',
    type: '图文类型',
    imageUrls: ['/activities/open-day.jpg'],
    status: '已通过',
    createdAt: '2026-06-09 22:40:00',
    updatedAt: '2026-06-09 22:40:00',
    likedBy: ['沈星', '林浅', '张悦', '周棠', '江野'],
    comments: [],
  },
  {
    id: 8,
    groupId: 1,
    author: '林浅',
    content: '配速组第一次破五，全员击掌。',
    type: '图文类型',
    imageUrls: ['/activities/basketball.jpg', '/activities/share.jpg'],
    status: '已通过',
    createdAt: '2026-06-19 21:15:00',
    updatedAt: '2026-06-19 21:15:00',
    likedBy: ['张悦', '江野'],
    comments: [],
  },
];
